// Models/AccountBalance.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ramza_EBike_Swabi.Models
{
    /// <summary>
    /// Single-row table that holds current cash and bank balances.
    /// Id is auto-generated by SQL Server — never set it manually.
    /// Always use FirstOrDefaultAsync() to retrieve it, not FindAsync(1).
    /// </summary>
    public class AccountBalance
    {
        [Key]
        public int Id { get; set; }   // ✅ No default — SQL Server identity assigns it

        [Column(TypeName = "decimal(18,2)")]
        public decimal CashBalance { get; set; } = 0;

        [Column(TypeName = "decimal(18,2)")]
        public decimal BankBalance { get; set; } = 0;

        [NotMapped]
        public decimal TotalBalance => CashBalance + BankBalance;
    }
}